#!/usr/bin/env python3
"""generate.sh — canon/-driven artifact generator for elite-role-constitution.

Reads canon/*.yaml, emits/updates derived files. Idempotent: a second
run produces no diff. CI gate runs `bash generate.sh && git diff
--exit-code` to catch manual edits to derived blocks.

Usage:
  bash generate.sh         # regenerate; write changes
  bash generate.sh --check # exit non-zero if any file would change
"""
from __future__ import annotations
import re
import subprocess
import sys
from pathlib import Path

import yaml  # pyyaml ≥ 5

ROOT = Path(__file__).resolve().parent

NUMBER_WORDS = {1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five",
                6: "Six", 7: "Seven", 8: "Eight", 9: "Nine", 10: "Ten",
                11: "Eleven", 12: "Twelve"}

# Canon source. Default: working tree at canon/*.yaml (the dev line).
# --version v2.0 overrides to canon/v2.0/*.yaml (a frozen released
# snapshot, per ROADMAP §5.G.G1). The canon/HEAD symlink points at
# the version considered "current released" and is used when --version
# HEAD is given. The working-tree default is intentionally separate
# from HEAD so the dev line can move ahead of any released version.
def _canon_dir() -> Path:
    for i, arg in enumerate(sys.argv):
        if arg == "--version" and i + 1 < len(sys.argv):
            return ROOT / "canon" / sys.argv[i + 1]
        if arg.startswith("--version="):
            return ROOT / "canon" / arg.split("=", 1)[1]
    return ROOT / "canon"


CANON_DIR = _canon_dir()


def load(name: str) -> dict:
    return yaml.safe_load((CANON_DIR / f"{name}.yaml").read_text())


def write_if_changed(path: Path, new: str, check_only: bool) -> bool:
    old = path.read_text() if path.exists() else None
    if old == new:
        return False
    if not check_only:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new)
    return True


# ── Hooks → .kimi/hooks.example.toml ─────────────────────────────────
def emit_hooks_toml(hooks: list[dict]) -> str:
    blocks = [
        "# {doc}\n[[hooks]]\nevent = \"{event}\"\nmatcher = \"{matcher}\"\n"
        "command = \"{script}\"\ntimeout = {timeout}".format(**h)
        for h in hooks
    ]
    return (
        "# .kimi/hooks.example.toml — regenerated by generate.sh from canon/hooks.yaml\n"
        "# DO NOT EDIT — run `bash generate.sh` instead.\n"
        "#\n"
        "# Append the [[hooks]] blocks below to your ~/.kimi/config.toml.\n"
        "# install.sh does this automatically (with a config.toml backup first).\n"
        "#\n"
        "# Hook protocol summary:\n"
        "#   stdin:  JSON event payload\n"
        "#   exit 0: allow (stdout appended to agent context)\n"
        "#   exit 2: block (stderr fed back to the LLM as correction)\n"
        "#   other:  allow with stderr logged only\n\n"
        + "\n\n".join(blocks) + "\n"
    )


# ── Patterns → .kimi/hooks/_patterns.sh ──────────────────────────────
def emit_patterns_sh(patterns: dict) -> str:
    block = patterns["protected_files"]["block"]
    wl = patterns["protected_files"]["whitelist"]
    catastrophic = patterns.get("catastrophic_paths", [])
    secrets = patterns["secrets"]

    out: list[str] = [
        "#!/usr/bin/env bash",
        "# .kimi/hooks/_patterns.sh — regenerated by generate.sh from canon/patterns.yaml",
        "# DO NOT EDIT — run `bash generate.sh` instead.",
        "#",
        "# Sourced by pre-tool-use.sh and pre-shell.sh.  Provides:",
        "#   PROTECTED_PATTERNS[]   WHITELIST_PATTERNS[]   CATASTROPHIC_PATHS[]",
        "#   SECRET_REGEX_<NAME>    SECRET_REGEX_ANY  (combined alternation)",
        "#",
        "# shellcheck disable=SC2034",
        "# (variables look unused when this file is shellchecked in isolation;",
        "# they are consumed by the scripts that `source` this file.)",
        "",
        "PROTECTED_PATTERNS=(",
    ]
    out += [f'    "{p}"' for p in block]
    out += [")", "", "WHITELIST_PATTERNS=("]
    out += [f'    "{p}"' for p in wl]
    out += [")", "", "# Catastrophic absolute paths — full-path match, not basename glob.",
            "CATASTROPHIC_PATHS=("]
    out += [f'    "{p}"' for p in catastrophic]
    out += [")", "", "# Secret content regexes"]
    for s in secrets:
        rx = s["regex"].replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'SECRET_REGEX_{s["name"].upper()}="{rx}"  # {s["source"]}')
    alts = "|".join(f'({s["regex"]})' for s in secrets)
    out += ["", "# Combined alternation — fast path for one-shot grep -qE",
            'SECRET_REGEX_ANY="' + alts.replace("\\", "\\\\").replace('"', '\\"') + '"', ""]
    return "\n".join(out)


# ── README.md updates (in-place line substitutions) ──────────────────
def update_readme(hooks: list[dict], file_count: int, text: str) -> str:
    n = len(hooks)
    word = NUMBER_WORDS.get(n, str(n))
    text = re.sub(
        r"^## Repo map \(\d+ files across (\d+) layers\)",
        f"## Repo map ({file_count} files across \\1 layers)",
        text, count=1, flags=re.MULTILINE,
    )
    text = re.sub(
        r"hooks/\*\.sh\s+\(\d+ lifecycle scripts",
        f"hooks/*.sh               ({n} lifecycle scripts",
        text,
    )
    text = re.sub(
        r"\*\*(Eight|Nine|Ten|Seven|Eleven|Twelve|\d+) lifecycle hooks\*\*",
        f"**{word} lifecycle hooks**", text,
    )
    text = re.sub(
        r"(?<=wires the )\b(eight|nine|ten|seven|eleven|twelve|\d+)\b",
        word.lower(), text, count=1,
    )
    return text


# ── SYSTEM_PROMPT_INSTALL.md ─────────────────────────────────────────
def update_system_prompt_install(hooks: list[dict], text: str) -> str:
    word = NUMBER_WORDS.get(len(hooks), str(len(hooks)))
    return re.sub(
        r"(or merge by hand\.\s+)(Eight|Nine|Seven|Ten|\d+)(\s+hooks are wired:)",
        f"\\1{word}\\3", text,
    )


# ── install.sh ───────────────────────────────────────────────────────
def update_install_sh(hooks: list[dict], text: str) -> str:
    return re.sub(
        r'"All \d+ hook scripts already executable\."',
        f'"All {len(hooks)} hook scripts already executable."',
        text,
    )


# ── 01_ELITE_ROLE.md §C.6 mapping table ──────────────────────────────
def update_elite_role_c6(laws: list[dict], text: str) -> str:
    table_lines = [
        "| Label | Section in this file | One-line definition |",
        "|---|---|---|",
    ] + [
        f'| **{law["id"]}** | {law["section_anchor"]} | {law["one_line"]} |'
        for law in laws
    ]
    block = (
        "<!-- canon-generated:laws-start -->\n"
        + "\n".join(table_lines)
        + "\n<!-- canon-generated:laws-end -->"
    )
    start = "<!-- canon-generated:laws-start -->"
    end = "<!-- canon-generated:laws-end -->"
    sc, ec = text.count(start), text.count(end)
    if sc > 1 or ec > 1:
        sys.stderr.write(
            f"ERROR: 01_ELITE_ROLE.md has duplicated canon-generated:laws markers "
            f"(start={sc}, end={ec}). Refusing to update — likely a prose paragraph "
            f"mentions the marker strings literally. Use phrasing like "
            f"\"the canon-generated markers\" instead of pasting the actual tokens.\n"
        )
        sys.exit(2)
    if sc != ec:
        sys.stderr.write(
            f"ERROR: marker imbalance in 01_ELITE_ROLE.md (start={sc}, end={ec}).\n"
        )
        sys.exit(2)
    if sc == 1:
        return re.sub(
            r"<!-- canon-generated:laws-start -->.*?<!-- canon-generated:laws-end -->",
            lambda _: block, text, flags=re.DOTALL,
        )
    sys.stderr.write(
        "WARN: 01_ELITE_ROLE.md §C.6 lacks canon-generated:laws markers; "
        "the L1-L7 table will NOT be auto-updated until the markers are added.\n"
    )
    return text


# ── Sanity checks ────────────────────────────────────────────────────
def sanity(hooks: list[dict]) -> None:
    """Verify canon agrees with filesystem ground truth."""
    on_disk = sorted((ROOT / ".kimi" / "hooks").glob("*.sh"))
    on_disk = [p.name for p in on_disk if p.name != "_patterns.sh"]
    declared = [Path(h["script"]).name for h in hooks]
    extra = set(on_disk) - set(declared)
    missing = set(declared) - set(on_disk)
    if extra:
        sys.stderr.write(f"ERROR: hook scripts on disk not in canon: {extra}\n")
        sys.exit(2)
    if missing:
        sys.stderr.write(f"ERROR: canon references missing scripts: {missing}\n")
        sys.exit(2)


# ── Main ─────────────────────────────────────────────────────────────
def main() -> int:
    check_only = "--check" in sys.argv

    hooks = load("hooks")["hooks"]
    patterns = load("patterns")
    laws = load("laws")["laws"]

    sanity(hooks)

    file_count = len(subprocess.check_output(
        ["git", "-C", str(ROOT), "ls-files"], text=True
    ).strip().splitlines())

    changed: list[str] = []
    targets = [
        (ROOT / ".kimi" / "hooks.example.toml", emit_hooks_toml(hooks)),
        (ROOT / ".kimi" / "hooks" / "_patterns.sh", emit_patterns_sh(patterns)),
        (ROOT / "README.md", update_readme(hooks, file_count, (ROOT / "README.md").read_text())),
        (ROOT / "SYSTEM_PROMPT_INSTALL.md",
         update_system_prompt_install(hooks, (ROOT / "SYSTEM_PROMPT_INSTALL.md").read_text())),
        (ROOT / "install.sh",
         update_install_sh(hooks, (ROOT / "install.sh").read_text())),
        (ROOT / "01_ELITE_ROLE.md",
         update_elite_role_c6(laws, (ROOT / "01_ELITE_ROLE.md").read_text())),
    ]
    for path, content in targets:
        if write_if_changed(path, content, check_only):
            changed.append(str(path.relative_to(ROOT)))

    if check_only:
        if changed:
            sys.stderr.write("generate.sh --check: derived files diverge from canon:\n")
            for c in changed:
                sys.stderr.write(f"  • {c}\n")
            sys.stderr.write("Run `bash generate.sh` and commit the result.\n")
            return 1
        print("generate.sh --check: canon and derived files are in sync.")
        return 0

    if changed:
        print("generate.sh updated:")
        for c in changed:
            print(f"  • {c}")
    else:
        print("generate.sh: no changes needed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
