#!/usr/bin/env bash
# .kimi/hooks/_patterns.sh — regenerated by generate.sh from canon/patterns.yaml
# DO NOT EDIT — run `bash generate.sh` instead.
#
# Sourced by pre-tool-use.sh and pre-shell.sh.  Provides:
#   PROTECTED_PATTERNS[]  WHITELIST_PATTERNS[]
#   SECRET_REGEX_<NAME>  SECRET_REGEX_ANY  (combined alternation)

PROTECTED_PATTERNS=(
    "*.env"
    "*.env.*"
    "*.envrc"
    "*.envrc.*"
    "*credentials"
    "*credentials.*"
    "*.credentials"
    "*.credentials.*"
    "id_rsa*"
    "id_dsa*"
    "id_ecdsa*"
    "id_ed25519*"
    "*authorized_keys*"
    "*.pem"
    "*.key"
    "*.p12"
    "*.pfx"
    "*.crt"
    "*.cer"
    "*.jks"
    "*.gpg"
    "*.asc"
    "secring.gpg"
    "*.netrc"
    "*pgpass*"
    "*.npmrc"
    "*.pypirc"
    "*kubeconfig*"
    "gcloud-key*.json"
    "*service-account*.json"
    "*terraform.tfstate"
    "*.tfstate"
    "*.tfstate.*"
)

WHITELIST_PATTERNS=(
    "*.env.example"
    "*.env.sample"
    "*.env.template"
    "*.env.dist"
    "*.env.test"
    ".env.example"
    "credentials.example.*"
)

# Secret content regexes
SECRET_REGEX_AWS_ACCESS_KEY="AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16}"  # AWS Identity Access Management (long-term + temporary STS keys)
SECRET_REGEX_OPENAI_LEGACY="sk-(ant-)?[A-Za-z0-9_-]{20,}"  # OpenAI legacy + Anthropic sk-ant- keys (same prefix shape)
SECRET_REGEX_OPENAI_PROJECT="sk-proj-[A-Za-z0-9_-]{20,}"  # OpenAI project-scoped key
SECRET_REGEX_GITHUB_PAT_CLASSIC="gh[pousr]_[A-Za-z0-9]{36,}"  # GitHub classic PAT (ghp_, gho_, ghu_, ghs_, ghr_ prefixes)
SECRET_REGEX_GITHUB_PAT_FINE="github_pat_[A-Za-z0-9_]{36,}"  # GitHub fine-grained personal access token
SECRET_REGEX_GOOGLE_API_KEY="AIza[0-9A-Za-z_-]{35}"  # Google API / Maps / GCP service key
SECRET_REGEX_SLACK_TOKEN="xox[abprs]-[A-Za-z0-9-]{10,}"  # Slack bot / user / refresh / webhook tokens
SECRET_REGEX_STRIPE_LIVE="sk_live_[A-Za-z0-9]{20,}"  # Stripe live secret key (test keys sk_test_ deliberately allowed for fixtures)
SECRET_REGEX_PEM_PRIVATE_KEY="-----BEGIN ([A-Z]+ ){0,2}PRIVATE KEY( BLOCK)?-----"  # PEM private key header — RSA, DSA, EC, OPENSSH, ENCRYPTED, PGP variants

# Combined alternation — fast path for one-shot grep -qE
SECRET_REGEX_ANY="(AKIA[0-9A-Z]{16}|ASIA[0-9A-Z]{16})|(sk-(ant-)?[A-Za-z0-9_-]{20,})|(sk-proj-[A-Za-z0-9_-]{20,})|(gh[pousr]_[A-Za-z0-9]{36,})|(github_pat_[A-Za-z0-9_]{36,})|(AIza[0-9A-Za-z_-]{35})|(xox[abprs]-[A-Za-z0-9-]{10,})|(sk_live_[A-Za-z0-9]{20,})|(-----BEGIN ([A-Z]+ ){0,2}PRIVATE KEY( BLOCK)?-----)"
