#!/bin/bash
# post-compact.sh — Elite Role hook for Kimi CLI 1.43+
#
# Event: PostCompact
# Purpose: verify COMPACT_STATE.md in the PROJECT cwd (from stdin JSON).
#
# v3.0 hardening:
#   - Uses _lib.sh helpers (cwd, ritual token verification, all-mtime check)
#   - Verifies ritual token generated by pre-compact.sh
#   - Checks all memory files are fresh (not just COMPACT_STATE.md)

set -euo pipefail

INPUT=$(cat 2>/dev/null || echo '{}')
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_lib.sh"

CWD=$(er_get_cwd "$INPUT")

if [ -z "$CWD" ] || [ ! -d "$CWD" ]; then
    echo "WARN: PostCompact — no valid cwd in event payload, skipping verification" >&2
    exit 0
fi

cd "$CWD"

echo "=== Elite Role · PostCompact verification ==="

if [ ! -f "memory/COMPACT_STATE.md" ]; then
    cat <<'EOF' >&2
BLOCKED by elite-role PostCompact hook (L1 UNKNOWN=STOP):
memory/COMPACT_STATE.md is missing — the compact ritual did not
produce a snapshot. Continuing now would silently lose cross-compact
continuity.
EOF
    exit 2
fi

# Verify ritual token from pre-compact.sh
if ! er_verify_ritual_token "memory/COMPACT_STATE.md"; then
    echo "WARN: memory/COMPACT_STATE.md missing valid ritual token" >&2
    echo "      The pre-compact hook may not have run correctly." >&2
fi

LINES=$(awk 'END{print NR}' memory/COMPACT_STATE.md)
MAX="$(grep -oP '(?<=^> \*\*Max Size:\*\* )\d+(?= lines)' memory/COMPACT_STATE.md 2>/dev/null | head -1 || true)"
MAX="${MAX:-40}"

if [ "$LINES" -gt "$MAX" ]; then
    echo "WARN: memory/COMPACT_STATE.md is $LINES lines > $MAX cap"
    echo "      Rotate per ROLLUP_POLICY.md before further compact cycles."
fi

# Check all memory files are fresh (post-compact consistency)
if [ -d "memory" ]; then
    if ! er_check_all_mtimes "memory" 300; then
        echo "WARN: Not all memory files are fresh (< 5 min) post-compact."
        echo "      Verify the save-state ritual was complete before compact."
    fi
fi

if [ -f "memory/CONTEXT.md" ]; then
    TASK_IN_CTX=$(grep -i "active task\|current task" memory/CONTEXT.md | head -1 || echo "")
    if [ -n "$TASK_IN_CTX" ]; then
        FIRST_WORD=$(echo "$TASK_IN_CTX" | awk -F': ' '{print $2}' | awk '{print $1}')
        if [ -n "$FIRST_WORD" ] && ! grep -qiF -- "$FIRST_WORD" memory/COMPACT_STATE.md; then
            echo "WARN: CONTEXT.md mentions task '$FIRST_WORD' but COMPACT_STATE.md does not"
            echo "      — verify the compact snapshot is for the current task."
        fi
    fi
fi

echo "PostCompact: COMPACT_STATE.md present, $LINES/$MAX lines."
exit 0
