#!/bin/bash
# scripts/compliance_dashboard.sh — Persist this week's compliance
# report to memory/compliance/YYYY-WW.md per ROADMAP_ELITE_v2 §5.F.F2.
#
# Usage:
#   bash scripts/compliance_dashboard.sh           # current ISO week
#   bash scripts/compliance_dashboard.sh --check   # exit 1 if file is stale
#
# The dashboard is bounded by memory/ROLLUP_POLICY.md (≤ 60 lines per
# weekly file). If F1's markdown ever grows past that cap, the
# rotation rule kicks in (currently a manual cleanup; automated
# pruning is a Phase F.F4 candidate if it ever matters).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DASH_DIR="memory/compliance"
ISO_WEEK="$(TZ=UTC date -u +%G-W%V)"   # e.g., 2026-W20
DASH_FILE="$DASH_DIR/${ISO_WEEK}.md"
MAX_LINES=60

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

if [ "$CHECK_ONLY" -eq 1 ]; then
    if [ ! -f "$DASH_FILE" ]; then
        echo "compliance_dashboard.sh: missing $DASH_FILE (no current-week dashboard)" >&2
        exit 1
    fi
    AGE_HOURS=$(( ( $(TZ=UTC date -u +%s) - $(stat -c %Y "$DASH_FILE") ) / 3600 ))
    if [ "$AGE_HOURS" -gt 168 ]; then
        echo "compliance_dashboard.sh: $DASH_FILE is $AGE_HOURS h old (>168 h); refresh needed" >&2
        exit 1
    fi
    echo "compliance_dashboard.sh: $DASH_FILE is current (age ${AGE_HOURS} h)"
    exit 0
fi

mkdir -p "$DASH_DIR"

{
    echo "# Compliance Dashboard — ${ISO_WEEK}"
    echo ""
    echo "> Generated by \`scripts/compliance_dashboard.sh\` (calls"
    echo "> \`scripts/compliance_report.sh\`). Bounded by ROLLUP_POLICY"
    echo "> at ${MAX_LINES} lines. Overwritten each week."
    echo "> Max Size: ${MAX_LINES} lines"
    echo ""
    bash "$REPO_ROOT/scripts/compliance_report.sh"
} > "$DASH_FILE.tmp"

# Enforce the rotation cap by truncation with a visible marker.
LINES="$(wc -l < "$DASH_FILE.tmp")"
if [ "$LINES" -gt "$MAX_LINES" ]; then
    head -n "$((MAX_LINES - 2))" "$DASH_FILE.tmp" > "$DASH_FILE"
    printf '\n[truncated: original was %s lines > %s cap]\n' "$LINES" "$MAX_LINES" >> "$DASH_FILE"
    rm -f "$DASH_FILE.tmp"
else
    mv "$DASH_FILE.tmp" "$DASH_FILE"
fi

echo "Wrote $DASH_FILE ($(wc -l < "$DASH_FILE") lines / ${MAX_LINES} cap)"
